import './globals.css'
import type { Metadata } from 'next'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'



export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lang
  }
}: {
  children: React.ReactNode ,
  params :{
    lang : string
  }
}) {
  console.log("lang  " , lang)
  return (
    <html lang={lang} dir={dir(lang)} >
      <body >{children}</body>
    </html>
  )
}
