import type { Metadata } from 'next'
import { StateProvider } from '@/providers/stateProvider'
import { AuthProvider } from '@/providers/userProvider'
import { LoggedHeader } from '@/components/layout/loggedHeader'






export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LoggedLayout({
  children,
  params ,
}: {
  children: React.ReactNode ,
  params :{
    lang : string
  } ,
}) {

  return (
<div className='bgBackground'  >   <AuthProvider> 
<LoggedHeader/>  
{children}  </AuthProvider>
</div>
  )
}
