import type { Metadata } from 'next'
import { dir } from 'i18next'
import { StateProvider } from '@/providers/stateProvider'
import { AuthProvider } from '@/providers/userProvider'






export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LoggedLayout({
  children,
  params ,
}: {
  children: React.ReactNode ,
  params :{
    lang : string
  } ,
}) {

  return (
<div className='bg-red-600' >   <AuthProvider>    {children}  </AuthProvider></div>
  )
}
