import type { Metadata } from 'next'
import { StateProvider } from '@/providers/stateProvider'
import { AuthProvider } from '@/providers/userProvider'
import { LoggedHeader } from '@/components/layout/loggedHeader'
import { Footer } from '@/components/layout/footer'






export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LoggedLayout({
  children,
  params ,
}: {
  children: React.ReactNode ,
  params :{
    lang : string
  } ,
}) {

  return (
    <AuthProvider> 
<div style={{maxWidth : '1500px'}} className="flex  w-full items-center justify-center pt-36  px-0 flex-col  gap-4 " >    
<LoggedHeader/>  
{children}
<Footer/>
</div>
</AuthProvider>

  )
}
