interface City{
    name : string ,
    lat : number ,
    long : number ,
    categories : {
        Historical: 0,
        Modern: 0,
        Nature: 0,
        Religious: 0,
        Cultural: 0,
        Culinary: 0,
        Adventure: 0,
        Romantic: 0,
        Beach: 0,
        familyFriendly: 0,
        Nightlife: 0,
        Wellness: 0,
        Shopping: 0,
        Festivals: 0,
        Sports: 0,
        EcoFriendly: 0,
        Educational: 0,
        hiddenGems: 0,
        Artistic: 0,
        Music: 0,
        techHub: 0,
        Architecture: 0,
        Literary: 0,
        Film: 0,
        Gaming: 0,
        Wildlife: 0,
        Mountains: 0,
        Desert: 0,
        Island: 0,
        Scenic: 0,
        Photography: 0,
        Diving: 0,
        Hiking: 0,
        Skiing: 0,
        waterSports: 0,
        historicLandmarks: 0,
        Gardens: 0,
        spaRelaxation: 0,
        craftsArtisans: 0,
        streetFood: 0,
        wineVineyards: 0,
        localFestivities: 0,
        fashionDesign: 0,
        sustainableLiving: 0,
        volunteeringOpportunities: 0,
        darkSkyWatching: 0,
        astroTourism: 0,
      };
}